/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Full Call Log Object includes the properties in the Call Log Summary Object, along with the following:
type CallLogFull struct {

	// ID
	Id string `json:"id,omitempty"`

	// Internal system id, may be null
	Uuid string `json:"uuid,omitempty"`

	// Account extension
	Extension ExtensionSummary `json:"extension,omitempty"`

	// Call made from this phone number
	CallerId string `json:"caller_id,omitempty"`

	// Call made to this phone number
	CalledNumber string `json:"called_number,omitempty"`

	// Call start time
	StartTime string `json:"start_time,omitempty"`

	// Call log creation time. Same as call end time + time needed to create call log
	CreatedAt string `json:"created_at,omitempty"`

	// Call direction: in or out
	Direction string `json:"direction,omitempty"`

	// Call type: call, fax, audiogram ...
	Type_ string `json:"type,omitempty"`

	// Call duration in seconds
	CallDuration int32 `json:"call_duration,omitempty"`

	// Was call being monitored?
	IsMonitored string `json:"is_monitored,omitempty"`

	// Internal system call reference number
	CallNumber string `json:"call_number,omitempty"`

	// Last action of call flow
	FinalAction string `json:"final_action,omitempty"`

	// URL of voicemail if available. User may download the audio via this URL. Empty string if voicemail does not exist
	VoicemailUrl string `json:"voicemail_url,omitempty"`

	// URL of voicemail if available. User may listen to the audio online via this URL. Empty string if voicemail does not exist
	VoicemailCpUrl string `json:"voicemail_cp_url,omitempty"`

	// Transcript of voicemail if enabled and available
	VoicemailTranscript string `json:"voicemail_transcript,omitempty"`

	// URL of call recording if available. User may download the audio via this URL. Empty string if call recording does not exist
	CallRecordingUrl string `json:"call_recording_url,omitempty"`

	// URL of call recording if available. User may listen to the audio online via this URL. Empty string if call recording does not exist
	CallRecordingCpUrl string `json:"call_recording_cp_url,omitempty"`

	// A list of call flows from beginning of call to end of call.
	Details []CallDetails `json:"details,omitempty"`

	// Internal system caller id / name
	CallerCnam string `json:"caller_cnam,omitempty"`
}
