/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CallbackObject struct {

	// URL of webhook, where the event is emitted to. Note: The listener supports both HTTP & HTTPS, we highly recommend that users use HTTPS on all callbacks (with user name and password) to ensure no one may send malicious events pretending to be Phone.com.
	Url string `json:"url,omitempty"`

	// Role of callback: main or backup
	Role string `json:"role,omitempty"`

	// HTTP method: get or post
	Verb string `json:"verb,omitempty"`

	// Optional user name needed to logon to the webhook URL
	Username string `json:"username,omitempty"`

	// Optional password needed to logon to the webhook URL
	Password string `json:"password,omitempty"`

	// Optional : Duration of HTTP response will time out while sending the event to the callback URL. (1 - 10 seconds)
	Timeout int32 `json:"timeout,omitempty"`
}
