/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreatePaymentParams struct {

	// Name of payment method
	Nickname string `json:"nickname,omitempty"`

	// primary, onfile or hidden
	Status string `json:"status,omitempty"`

	// Credit Card Type
	Type_ string `json:"type,omitempty"`

	// Credit Card Token. Token is obtained by entering credit card info via the Credit Card Entry Form
	CcToken string `json:"cc_token,omitempty"`
}
