/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreateRedirectUriParams struct {

	// Redirect URI string for use in redirect-based flows such as the authorization code and implicit flows
	RedirectUri string `json:"redirect_uri,omitempty"`
}
