/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreatePhoneNumberParams struct {

	// Phone number
	PhoneNumber interface{} `json:"phone_number,omitempty"`

	// Route lookup object
	Route interface{} `json:"route,omitempty"`

	// Phone Name
	Name string `json:"name,omitempty"`

	// Block incoming calls
	BlockIncoming string `json:"block_incoming,omitempty"`

	// Block anonymous calls
	BlockAnonymous string `json:"block_anonymous,omitempty"`

	CallerId CallerIdPhoneNumber `json:"caller_id,omitempty"`

	SmsForwarding SmsForwardingParams `json:"sms_forwarding,omitempty"`

	CallNotifications CallNotifications `json:"call_notifications,omitempty"`
}
