/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreateListenerParams struct {

	// Type of listener. Must be 'callback'
	Type_ string `json:"type,omitempty"`

	// Type of event to subscribe. 'call.new', 'call.update', 'call.complete'
	EventType string `json:"event_type,omitempty"`

	// Array of Callback Objects.
	Callbacks []CallbackObject `json:"callbacks,omitempty"`
}
