/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreateOauthParams struct {

	// authorization_code, client_credentials, password or refresh_token
	GrantType string `json:"grant_type,omitempty"`

	// Client ID
	ClientId string `json:"client_id,omitempty"`

	// Client Secret Key
	ClientSecret string `json:"client_secret,omitempty"`

	// Authorization Code created via the /oauth/authorization API
	Code string `json:"code,omitempty"`

	// The redirect URI where user enters authentication information
	RedirectUri string `json:"redirect_uri,omitempty"`

	// account-owner, extension-user and/or methods:ALL, separated by space (%20)
	Scope string `json:"scope,omitempty"`

	// User name
	Username string `json:"username,omitempty"`

	// Password
	Password string `json:"password,omitempty"`

	// Refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}
