/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type FilterVoicemailArray struct {

	Id string `json:"id,omitempty"`

	From string `json:"from,omitempty"`

	To string `json:"to,omitempty"`

	IsNew string `json:"is_new,omitempty"`

	CreatedAt int32 `json:"created_at,omitempty"`

	Extension string `json:"extension,omitempty"`
}
