/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Each entry in a Voicemail's from list is an object with the following properties:
type FromObject struct {

	// The caller phone number
	Number string `json:"number,omitempty"`

	// The name / caller ID of the caller
	Name string `json:"name,omitempty"`

	// The city where the caller is from
	City string `json:"city,omitempty"`

	// The state where the caller is from
	State string `json:"state,omitempty"`
}
