/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type GetOauthAccessToken struct {

	Scope string `json:"scope,omitempty"`

	ExpiresAt int32 `json:"expires_at,omitempty"`

	ScopeDetails []ScopeDetails `json:"scope_details,omitempty"`
}
