/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Listener Object is used to represent a listener. Here are the properties:
type ListenerFull struct {

	// Integer ID. Read-only.
	Id int32 `json:"id,omitempty"`

	VoipId int32 `json:"voip_id,omitempty"`

	// Type of listener: callback
	Type_ string `json:"type,omitempty"`

	// Type of event subscribed by the listener: call.new, call.update, call.complete, call.log, sms.in, sms.out
	EventType string `json:"event_type,omitempty"`

	// Array of Callback Object
	Callbacks []interface{} `json:"callbacks,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty"`

	CreatedAt int32 `json:"created_at,omitempty"`
}
