/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Full Recording Object and the Summary Recording Object are the same.
type MediaFull struct {

	// Recording ID. Read-only.
	Id int32 `json:"id,omitempty"`

	// Name of recording
	Name string `json:"name,omitempty"`

	// Can be hold_music or greeting. Indicates the purpose of this recording and where it can be used.
	Type_ string `json:"type,omitempty"`
}
