/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Call Notifications object configures the recipient(s) of notifications when calls are received to this extension.
type Notification struct {

	// Array of email addresses
	Emails []string `json:"emails,omitempty"`

	// Phone number capable of receiving SMS messages
	Sms string `json:"sms,omitempty"`
}
