/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// An OAuth Client Full Object is identical as a Summary Object.
type OauthClientFull struct {

	// Client ID
	Id int32 `json:"id,omitempty"`

	// Name of Client
	ClientName string `json:"client_name,omitempty"`
}
