/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Payment Method Full Object contains the same properties as the Payment Method Summary Object, along with the following:
type PaymentFull struct {

	// Payment Method ID
	Id int32 `json:"id,omitempty"`

	// API Account ID
	VoipId int32 `json:"voip_id,omitempty"`

	// 'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card;
	Status string `json:"status,omitempty"`

	// Name of Card
	Nickname string `json:"nickname,omitempty"`

	// 'cc' for credit card
	Type_ string `json:"type,omitempty"`

	// Time payment record is created
	CreatedAt int32 `json:"created_at,omitempty"`

	// Detail of contact person
	Contact ContactResponse `json:"contact,omitempty"`

	// Number of times the payment method was declined
	DeclineCount int32 `json:"decline_count,omitempty"`

	// Next billing date
	NextChargeDate int32 `json:"next_charge_date,omitempty"`

	// Last time the payment method was updated
	UpdatedAt int32 `json:"updated_at,omitempty"`

	// Encrypted credit card token to be used for billing
	CcToken string `json:"cc_token,omitempty"`

	// Credit card number partially masked with xxxxxxxx
	CcNumber string `json:"cc_number,omitempty"`

	// Credit card expiration date
	CcExp string `json:"cc_exp,omitempty"`
}
