/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Payment Method Summary Object is used to briefly represent a Credit Card. It consists of parameters in the table below:
type PaymentSummary struct {

	// Payment Method ID
	Id int32 `json:"id,omitempty"`

	// API Account ID
	VoipId int32 `json:"voip_id,omitempty"`

	// 'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card;
	Status string `json:"status,omitempty"`

	// Name of Card
	Nickname string `json:"nickname,omitempty"`

	// 'cc' for credit card
	Type_ string `json:"type,omitempty"`

	// Time payment record is created
	CreatedAt int32 `json:"created_at,omitempty"`
}
