/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PricingObject struct {

	// Pricing code / ID
	Id int32 `json:"id,omitempty"`

	// Name of pricing plan
	Name string `json:"name,omitempty"`
}
