/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Full Pricing Object is identical to the Pricing Summary Object. The Pricing Summary Object is used to briefly represent a pricing plan. Here are the properties:
type PricingFull struct {

	// Integer ID of this object.
	Id int32 `json:"id,omitempty"`

	// Pricing Object
	Pricing PricingObject `json:"pricing,omitempty"`

	// Phone.com API Account (VoIP) ID
	VoipId int32 `json:"voip_id,omitempty"`

	// Reason this pricing plan is applied
	Reason string `json:"reason,omitempty"`

	// Name of the person / process who added this pricing plan to the subaccount
	Who string `json:"who,omitempty"`

	// Pricing plan expiration timestamp in unix format. If pricing plan never expires, this item will not be returned
	ExpireDate string `json:"expire_date,omitempty"`
}
