/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RedirectUriFull struct {

	// Redirect URI ID
	Id int32 `json:"id,omitempty"`

	// The Uniform Resource Identifier is a string used to identify the path to be redirected
	Uri string `json:"uri,omitempty"`

	// redirect
	Type_ string `json:"type,omitempty"`
}
