/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ReplaceExtensionParams struct {

	// Voicemail object
	Voicemail Voicemail `json:"voicemail,omitempty"`

	// Call Notifications object
	CallNotifications CallNotifications `json:"call_notifications,omitempty"`

	// Recording lookup object
	NameGreeting interface{} `json:"name_greeting,omitempty"`

	// Name (required)
	Name string `json:"name,omitempty"`

	// Timezone
	Timezone string `json:"timezone,omitempty"`

	// Include in dial-by-name directory
	IncludeInDirectory bool `json:"include_in_directory,omitempty"`

	// Extension number (required)
	Extension int32 `json:"extension,omitempty"`

	// Enable outgoing calls
	EnableOutboundCalls bool `json:"enable_outbound_calls,omitempty"`

	// Extension type
	UsageType string `json:"usage_type,omitempty"`

	// Contact name
	FullName string `json:"full_name,omitempty"`

	// Enable Call Waiting
	EnableCallWaiting bool `json:"enable_call_waiting,omitempty"`

	// Caller ID
	CallerId string `json:"caller_id,omitempty"`

	// Local area code
	LocalAreaCode int32 `json:"local_area_code,omitempty"`

	// Route object lookup (must belong to this extension)
	Route string `json:"route,omitempty"`
}
