/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Full Voicemail Object includes all of the properties in the Voicemail Summary Object.
type VoicemailFull struct {

	// Unique Voicemail ID. Read-only.
	Id string `json:"id,omitempty"`

	// Name. Required.
	DownloadUrl string `json:"download_url,omitempty"`

	// Extension where the voicemail is saved into.
	Extension ExtensionSummary `json:"extension,omitempty"`

	// The caller's information
	From FromObject `json:"from,omitempty"`

	// The phone number where the caller is calling
	To string `json:"to,omitempty"`

	// True when Voicemail is new; False when Voicemail has been listened
	IsNew bool `json:"is_new,omitempty"`

	// Date string representing the UTC time that the object was created in the Phone.com API system.
	CreatedAt int32 `json:"created_at,omitempty"`

	// Folder name where voicemail is saved
	Folder string `json:"folder,omitempty"`

	// Length of voicemail in seconds
	Duration int32 `json:"duration,omitempty"`
}
